version: '3'
services:
  app1:
    build:
      context: .
    env_file:
      - ./environments/db.env
    # command: bundle exec puma -C config/puma.rb
    # command: bundle exec rails s -b 192.168.33.10
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app1
      - public-data:/app1/public
      - tmp-data:/app1/tmp
      - log-data:/app1/log
    depends_on:
      - db
  db:
    build: ./containers/mysql
    # image: mysql:5.7
    # image: mysql:8.0.24
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/app1/public
      - tmp-data:/app1/tmp
    ports:
      - 80:80
    depends_on:
      - app1
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: