version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec rails s -b 192.168.33.10 -p 80
    volumes:
      - .:/app1
      - public-data:/app1/public
      - tmp-data:/app1/tmp
      - log-data:/app1/log
    depends_on:
      - db
  db:
    # build:
    #   context: containers/mysql
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/app1/public
      - tmp-data:/app1/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: